version: '3'

services:

  modbus-simulator-server:
    container_name: modbus-simulator-server
    build:
      context: ./modbus-simulator
    ports:
      - 5020:5020
    networks:
      - smartpulse-bridge

  rabbitmq-server:
    image: rabbitmq:management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - smartpulse-bridge
    
  modbus-reader:
    container_name: modbus-reader
    build:
      context: ./modbus-reader
    networks:
      - smartpulse-bridge

  rabbitmq-consumer:
    container_name: rabbitmq-consumer
    depends_on:
      - rabbitmq-server
    build:
      context: ./rabbitmq-consumer
    ports:
      - 8001:8001
    networks:
      - smartpulse-bridge
    restart: always

  prometheus-server:
    container_name: prometheus-server
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/prometheus-data/:/prometheus-data/"
    command:
      - "--storage.tsdb.path=/prometheus-data"
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - smartpulse-bridge
    ports:
      - 9090:9090

  grafana-server:
    container_name: grafana_server
    image: grafana/grafana
    links:
      - influx-db
    depends_on:
      - prometheus-server
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - smartpulse-bridge

  influx-db:
    container_name: influx-db
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=smartpulse
      - DOCKER_INFLUXDB_INIT_PASSWORD=WDb3#Je9h4q6l
      - DOCKER_INFLUXDB_INIT_ORG=sp
      - DOCKER_INFLUXDB_INIT_BUCKET=spb
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=RAlhlqCqwmGdeZj00UdyA5NAwDqZoJK6tufeoF6gN7W6ckhdjJ6bgreWgowS6JIAxQbDk4wAsgY_FN5SAV_qTw==
    ports:
      - 8086:8086
    volumes:
      - ./influx-db/influx-data:/var/lib/influxdb2
    networks:
      - smartpulse-bridge
      
networks:
  smartpulse-bridge:
    driver: bridge